### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/razor-sharp#3]
Epic: #2

As a **user** I can **create an account** so that **I can access my saved orders, profile & not have to re-enter my information.**

### Acceptance Criteria

 - This story will be completed when a new user can sign up to the website and then proceed to login and logout with their personal information. 
 - The user should not be able to view or access the admin panel of the website
 - The user should be logged in to an account that is unique to them.

### Tasks

 - [x] - Install Django-Allauth
 - [x] - Create Template
 - [x] - Create logic
 - [x] - Test Create account
 - [x] - Test login / logout
 - [x] - Test user accessing admin panel
