### ISSUE TITLE
USER STORY: Password Reset

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/razor-sharp#4]
Epic: #2 

As a **user** I can **request a password reset** so that **I can access my account if I forgot the old password**

### Acceptance Criteria
This story will be complete once the user can successfully change their password reset.

### Tasks

 - [ ] - Edit password reset templates
 - [ ] - make sure reset emails are being sent
 - [ ] - Test password reset email to ensure user can login once successfully changed.
