### ISSUE TITLE
USER STORY: View Products

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/razor-sharp#5]
Epic: #

As a **customer** I can **view products** so that **I can choose something to buy**

### Acceptance Criteria
This task will be completed once the products are displayed in their intended location and customers can access them.

### Tasks

 - [x] - create products view
 - [x] - create a products template
 - [x] - create a products model
 - [x] - add sample products to store
 - [x] - test products are showing up correctly
